name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Prettier
        run: pnpm prettier
      - name: Eslint
        run: pnpm eslint
